/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_sadithramos;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Pantalla extends javax.swing.JFrame {
 static ArrayList <Torneo> torneos = new ArrayList();
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        setLocationRelativeTo(null);
        jt_Torneo.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaAdmin = new javax.swing.JDialog();
        crear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Torneo = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_participantes = new javax.swing.JList<>();
        CerrarTorneo = new javax.swing.JButton();
        MarcarGanador = new javax.swing.JButton();
        CrearTorneo = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        Nombre_Torneo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        rondas = new javax.swing.JTextField();
        PantallaParticipante = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        Nombre_Usuario = new javax.swing.JTextField();
        Participante = new javax.swing.JButton();
        Admin = new javax.swing.JButton();

        PantallaAdmin.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                PantallaAdminWindowClosing(evt);
            }
        });

        crear.setBackground(new java.awt.Color(0, 0, 255));
        crear.setText("Crear Torneo");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        jt_Torneo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jt_TorneoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Torneo);

        jLabel2.setText("Torneos");

        jLabel3.setText("Personas dentro del Torneo");

        jScrollPane2.setViewportView(jt_participantes);

        CerrarTorneo.setBackground(new java.awt.Color(255, 0, 0));
        CerrarTorneo.setText("Cerrar Torneo");
        CerrarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarTorneoActionPerformed(evt);
            }
        });

        MarcarGanador.setBackground(new java.awt.Color(255, 0, 0));
        MarcarGanador.setText("Marcar Ganador ");
        MarcarGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcarGanadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaAdminLayout = new javax.swing.GroupLayout(PantallaAdmin.getContentPane());
        PantallaAdmin.getContentPane().setLayout(PantallaAdminLayout);
        PantallaAdminLayout.setHorizontalGroup(
            PantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaAdminLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(74, 74, 74))
            .addGroup(PantallaAdminLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(CerrarTorneo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MarcarGanador)
                .addGap(80, 80, 80))
            .addGroup(PantallaAdminLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PantallaAdminLayout.createSequentialGroup()
                        .addComponent(crear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PantallaAdminLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        PantallaAdminLayout.setVerticalGroup(
            PantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaAdminLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(PantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(PantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(PantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CerrarTorneo)
                    .addComponent(MarcarGanador))
                .addGap(121, 121, 121))
        );

        jLabel4.setText("Nombre del Torneo");

        jLabel5.setText("Rondas");

        Crear.setBackground(new java.awt.Color(0, 0, 255));
        Crear.setText("Crear Torneo");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearTorneoLayout = new javax.swing.GroupLayout(CrearTorneo.getContentPane());
        CrearTorneo.getContentPane().setLayout(CrearTorneoLayout);
        CrearTorneoLayout.setHorizontalGroup(
            CrearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTorneoLayout.createSequentialGroup()
                .addGroup(CrearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearTorneoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(CrearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(Nombre_Torneo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rondas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CrearTorneoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        CrearTorneoLayout.setVerticalGroup(
            CrearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTorneoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nombre_Torneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rondas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        PantallaParticipante.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                PantallaParticipanteWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout PantallaParticipanteLayout = new javax.swing.GroupLayout(PantallaParticipante.getContentPane());
        PantallaParticipante.getContentPane().setLayout(PantallaParticipanteLayout);
        PantallaParticipanteLayout.setHorizontalGroup(
            PantallaParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        PantallaParticipanteLayout.setVerticalGroup(
            PantallaParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre de Usuario: ");

        Participante.setBackground(new java.awt.Color(51, 51, 255));
        Participante.setText("Participante");
        Participante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParticipanteActionPerformed(evt);
            }
        });

        Admin.setBackground(new java.awt.Color(255, 0, 0));
        Admin.setText("Administrador");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Participante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(Nombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Nombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Participante)
                    .addComponent(Admin))
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarTorneoActionPerformed
        // TODO add your handling code here:
       int opcion = jt_Torneo.getSelectedIndex();
       if(opcion == -1){
           JOptionPane.showMessageDialog(this, "NO SELECCIONO UN TORNEO");
       }else{
          modeloLista.remove(opcion);
          torneos.get(opcion).setFlag(false);
       }
    }//GEN-LAST:event_CerrarTorneoActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        PantallaAdmin.pack();
        PantallaAdmin.setLocationRelativeTo(null);
        PantallaAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        CrearTorneo.pack();
        CrearTorneo.setLocationRelativeTo(null);
        CrearTorneo.setVisible(true);
        
    }//GEN-LAST:event_crearActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        String nombre = Nombre_Torneo.getText();
        ArrayList<String> p = new ArrayList();
        Torneo t = new Torneo(nombre,true,true,"",p);
        torneos.add(t);
        modeloLista.addElement(t);
    }//GEN-LAST:event_CrearActionPerformed

    private void PantallaAdminWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PantallaAdminWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_PantallaAdminWindowClosing

    private void PantallaParticipanteWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PantallaParticipanteWindowClosing
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_PantallaParticipanteWindowClosing

    private void ParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParticipanteActionPerformed
        // TODO add your handling code here:
        PantallaParticipante.pack();
        PantallaParticipante.setLocationRelativeTo(null);
        PantallaParticipante.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ParticipanteActionPerformed

    private void MarcarGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcarGanadorActionPerformed
        // TODO add your handling code here:
        int opcion = jt_participantes.getSelectedIndex();
        String nombre = jt_participantes.getSelectedValue();
       if(opcion == -1){
           JOptionPane.showMessageDialog(this, "NO SELECCIONO UN GANADOR");
       }else{
          torneos.get(opcion).setGanador(nombre);
       }
    }//GEN-LAST:event_MarcarGanadorActionPerformed

    private void jt_TorneoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jt_TorneoValueChanged
        // TODO add your handling code here:
        System.out.println("hola");
    }//GEN-LAST:event_jt_TorneoValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }
    DefaultListModel modeloLista = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton CerrarTorneo;
    private javax.swing.JButton Crear;
    private javax.swing.JDialog CrearTorneo;
    private javax.swing.JButton MarcarGanador;
    private javax.swing.JTextField Nombre_Torneo;
    private javax.swing.JTextField Nombre_Usuario;
    private javax.swing.JDialog PantallaAdmin;
    private javax.swing.JDialog PantallaParticipante;
    private javax.swing.JButton Participante;
    private javax.swing.JButton crear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jt_Torneo;
    private javax.swing.JList<String> jt_participantes;
    private javax.swing.JTextField rondas;
    // End of variables declaration//GEN-END:variables
}
